name: music
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  local_auth: ^2.3.0
  just_audio: ^0.9.42
  file_picker: ^8.1.4
  firebase_analytics: ^11.3.5
  flutter_pdfview: ^1.3.4
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/sound-new.jpg"  # Ruta a tu ícono

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/img/

